<a href="https://colab.research.google.com/github/Richard01072002/exp1_deep/blob/main/exp1_deep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5])


In [ ]:
# Print the type of data held by the tensor
print(x.dtype)

torch.int64


In [ ]:
print(type(x))
print(x.type())

<class 'torch.Tensor'>
torch.LongTensor


In [ ]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [ ]:
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4])


In [ ]:
# Using torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[2]=77
print(t)

tensor([0, 1, 2, 3, 4])


In [ ]:
data = np.array([1,2,3])

In [ ]:
a = torch.Tensor(data)  # Equivalent to cc = torch.FloatTensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [ ]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3]) torch.LongTensor


In [ ]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3]) torch.LongTensor


In [ ]:
x = torch.empty(4, 3)
print(x)

tensor([[4.3833e-26, 4.5792e-41, 1.3456e-33],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.7052e+31, 7.2148e+22]])


In [ ]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [ ]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


In [ ]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


In [ ]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


In [ ]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


In [ ]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


In [ ]:
x = torch.rand(4, 3)
print(x)

tensor([[0.5343, 0.3249, 0.8055],
        [0.9579, 0.1261, 0.4865],
        [0.1171, 0.7514, 0.3270],
        [0.9185, 0.6133, 0.7278]])


In [ ]:
x = torch.randn(4, 3)
print(x)

tensor([[ 1.6166, -0.1519, -0.6896],
        [-0.5726,  0.3230,  0.6043],
        [ 0.7863, -1.7243, -2.0150],
        [ 0.4203,  0.2467,  0.2944]])


In [ ]:
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[4, 2, 4],
        [2, 4, 1],
        [3, 1, 2],
        [0, 4, 0]])


In [ ]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.7998,  1.4048,  0.6740,  1.1583,  2.8587],
        [-1.5296,  0.7151,  1.0462,  1.4426,  0.1422]])


In [ ]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x.size()

torch.Size([2, 3])

In [ ]:
x.device

device(type='cpu')

In [ ]:
x.layout

torch.strided